minimal_mistakes_skin    : "default" 
                           # "default" "air", "aqua", "contrast", "dark"
                           # "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-EN"    # 블로그의 주요 언어입니다. 한국어로 보려고 ko-KR로 설정했습니다.
title                    : ["Ji Yoon Rhee Portfolio"]  # 사이트 탭에서 보이는 이름입니다.
name                     : [Ji Yoon Rhee]      # 화면 하단 영역의 이름입니다.
description              : [Portfolio website]   # 설명란입니다. (어디 적용되는지 모르겠네요...) 
url                      : [https://nerobero.github.io] # 현재의 블로그 url 입니다.
repository               : [https://github.com/nerobero/nerobero.github.io] # Github Repo url입니다.
teaser                   : # 폴백일 때 보일 이미지입니다. "assets/images/"로 연결됩니다.
logo                     : # 화면에 보여지는 logo 이미지입니다. "assets/images"로 세팅합니다.
masthead_title           : [angelas game portfolio]     # 화면 title 입니다.


# Site Theme application
remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
